# Generated by Django 4.2.27 on 2025-12-05 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANIME', 'Anime'), ('PELICULA', 'Película'), ('SERIE', 'Serie'), ('MANGA', 'Manga'), ('LIBRO', 'Libro')], max_length=10)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('titulo_alternativo', models.CharField(blank=True, max_length=400, null=True)),
                ('sinopsis', models.TextField()),
                ('año_lanzamiento', models.PositiveIntegerField()),
                ('temporadas', models.PositiveIntegerField(blank=True, null=True)),
                ('episodios', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos.')),
                ('tomos', models.PositiveIntegerField(blank=True, null=True)),
                ('capitulos', models.PositiveIntegerField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('saga', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('COMPLETO', 'Completo'), ('EN_EMISION', 'En emisión'), ('CANCELADO', 'Cancelado'), ('PROXIMO', 'Próximo')], default='COMPLETO', max_length=15)),
                ('estado_visualizacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VIENDO', 'Actualmente viendo'), ('VISTO', 'Visto'), ('EN_PAUSA', 'En pausa')], default='PENDIENTE', max_length=15)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.genero')),
            ],
            options={
                'verbose_name_plural': 'Contenidos Multimedia',
                'ordering': ['-fecha_agregado'],
            },
        ),
    ]
